@echo off
echo Starting both .NET API and React App...
echo.

echo Starting .NET API in background...
start "API" cmd /k "cd /d "%~dp0Backend\BlogApi" && dotnet run"

echo Waiting 3 seconds for API to start...
timeout /t 3 /nobreak > nul

echo Starting React App...
npm run dev
